"""Enhanced metadata configuration for knowledge base documents"""

DOCUMENT_METADATA = {
    # === PROFILE ===
    "profile.md": {
        "title": "Deepanshu Malik - Profile",
        "subcategory": "overview",
        "content_type": "narrative",
        "section": "Basic Information",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": [],
        "concepts": ["profile", "experience", "certification", "contact", "projects", "portfolio"],
        "keywords": ["senior", "backend", "engineer", "fintech", "CKA", "kubernetes", "projects", "how many", "total", "portfolio"],
        "question_types": ["who", "what", "contact", "how many"],
        "intent_relevance": {"quick_answer": 1.0, "tour": 1.0, "general": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "shallow",
    },
    "education.md": {
        "title": "Education",
        "subcategory": "background",
        "content_type": "list",
        "section": "Education",
        "date_start": "2014-06",
        "date_end": "2021",
        "recency_score": 0.3,
        "company": "personal",
        "technologies": [],
        "concepts": ["education", "degree", "university"],
        "keywords": ["MCA", "computer", "science", "university"],
        "question_types": ["what", "where"],
        "intent_relevance": {"quick_answer": 1.0, "tour": 0.5},
        "has_code": False,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "shallow",
    },
    # === EXPERIENCE ===
    "tradeindia.md": {
        "title": "Tradeindia.com Experience",
        "subcategory": "backend",
        "content_type": "narrative",
        "section": "Work Experience",
        "date_start": "2021-04",
        "date_end": "2022-05",
        "recency_score": 0.4,
        "company": "Tradeindia.com",
        "technologies": ["Python", "Django", "Elasticsearch", "REST"],
        "concepts": ["API", "search", "optimization", "testing"],
        "keywords": ["first", "role", "elasticsearch", "search", "API", "testing"],
        "question_types": ["what", "how", "where"],
        "intent_relevance": {"experience_deepdive": 1.0, "skill_assessment": 0.7},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "voereir.md": {
        "title": "VoerEir AB Experience",
        "subcategory": "devops",
        "content_type": "narrative",
        "section": "Work Experience",
        "date_start": "2022-05",
        "date_end": "2024-03",
        "recency_score": 0.6,
        "company": "VoerEir AB",
        "technologies": ["Python", "Flask", "Kubernetes"],
        "concepts": ["monitoring", "deployment", "mentorship", "agile"],
        "keywords": ["kubernetes", "monitoring", "deployment", "mentorship"],
        "question_types": ["what", "how"],
        "intent_relevance": {"experience_deepdive": 1.0, "skill_assessment": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "capri.md": {
        "title": "Capri Global Experience",
        "subcategory": "backend",
        "content_type": "narrative",
        "section": "Work Experience",
        "date_start": "2024-07",
        "date_end": "2025-03",
        "recency_score": 0.9,
        "company": "Capri Global",
        "technologies": ["Python", "FastAPI", "asyncio", "Docker", "Jenkins", "MySQL"],
        "concepts": ["async", "performance", "optimization", "ETL", "CI/CD"],
        "keywords": ["fastapi", "async", "performance", "loan", "ETL", "multiprocessing"],
        "question_types": ["what", "how"],
        "intent_relevance": {"experience_deepdive": 1.0, "skill_assessment": 0.9},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "kogta.md": {
        "title": "Kogta Financial Experience",
        "subcategory": "backend",
        "content_type": "narrative",
        "section": "Work Experience",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "Kogta Financial",
        "technologies": ["Python", "FastAPI", "Flask", "MongoDB", "MySQL", "OpenSearch", "RedShift", "AWS", "EKS", "SQS", "Kubernetes", "Helm", "Jenkins", "GitLab"],
        "concepts": ["microservices", "mentorship", "automation", "optimization", "multi-db"],
        "keywords": ["senior", "microservices", "opensearch", "sqs", "eks", "mentorship"],
        "question_types": ["what", "how"],
        "intent_relevance": {"experience_deepdive": 1.0, "skill_assessment": 1.0, "project_deepdive": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "deep",
    },
    # === SKILLS ===
    "languages.md": {
        "title": "Programming Languages",
        "subcategory": "backend",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "FastAPI", "Flask", "Django", "asyncio", "multiprocessing"],
        "concepts": ["programming", "backend", "async", "performance"],
        "keywords": ["python", "expert", "async", "production"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.9},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "databases.md": {
        "title": "Database Experience",
        "subcategory": "database",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["MongoDB", "MySQL", "OpenSearch", "Elasticsearch", "RedShift"],
        "concepts": ["database", "optimization", "query", "schema"],
        "keywords": ["mongodb", "mysql", "opensearch", "optimization", "query"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.9},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "devops.md": {
        "title": "Cloud & DevOps Skills",
        "subcategory": "devops",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["AWS", "EKS", "SQS", "Kubernetes", "Docker", "Helm", "Jenkins", "GitLab"],
        "concepts": ["cloud", "devops", "kubernetes", "CI/CD", "deployment"],
        "keywords": ["aws", "kubernetes", "CKA", "docker", "helm", "CI/CD"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.9},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "frameworks.md": {
        "title": "Frameworks & Libraries",
        "subcategory": "backend",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["FastAPI", "Flask", "Django", "LangChain"],
        "concepts": ["framework", "API", "async", "microservices"],
        "keywords": ["fastapi", "flask", "django", "langchain", "expert"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.9},
        "has_code": False,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "genai_skills.md": {
        "title": "GenAI & LLM Skills",
        "subcategory": "genai",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2025-01",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["OpenAI", "ChromaDB", "tiktoken", "LangChain"],
        "concepts": ["RAG", "embeddings", "LLM", "prompt", "streaming", "reranking", "hybrid_search"],
        "keywords": ["RAG", "LLM", "OpenAI", "embeddings", "prompt", "streaming", "ChromaDB"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.9, "project_deepdive": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "aws_sqs.md": {
        "title": "AWS SQS Patterns",
        "subcategory": "backend",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["AWS", "SQS", "Python"],
        "concepts": ["queue", "async", "messaging", "FIFO", "deduplication"],
        "keywords": ["SQS", "queue", "FIFO", "async", "messaging", "AWS"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "code_walkthrough": 0.9},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": True,
        "detail_level": "deep",
    },
    "beanie_odm.md": {
        "title": "Beanie ODM (MongoDB Async)",
        "subcategory": "database",
        "content_type": "technical",
        "section": "Skills",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Beanie", "MongoDB", "Python", "FastAPI"],
        "concepts": ["ODM", "async", "database", "validation", "aggregation"],
        "keywords": ["beanie", "mongodb", "async", "ODM", "pydantic"],
        "question_types": ["what", "how"],
        "intent_relevance": {"skill_assessment": 1.0, "code_walkthrough": 0.9},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "deep",
    },
    # === PROJECTS ===
    "portfolio_ai_backend.md": {
        "title": "Portfolio AI Backend",
        "subcategory": "genai",
        "content_type": "technical",
        "section": "Projects",
        "date_start": "2025-12",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["FastAPI", "OpenAI", "ChromaDB", "tiktoken", "Python"],
        "concepts": ["RAG", "hybrid_search", "reranking", "intent", "streaming", "token_management"],
        "keywords": ["RAG", "chatbot", "portfolio", "hybrid", "reranking", "intent", "streaming"],
        "question_types": ["what", "how", "architecture"],
        "intent_relevance": {"project_deepdive": 1.0, "code_walkthrough": 0.9, "skill_assessment": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": True,
        "detail_level": "deep",
    },
    "genai_sandbox.md": {
        "title": "GenAI Sandbox",
        "subcategory": "genai",
        "content_type": "narrative",
        "section": "Projects",
        "date_start": "2025-11",
        "date_end": "2025-12",
        "recency_score": 0.9,
        "company": "personal",
        "technologies": ["Python", "OpenAI", "ChromaDB", "asyncio"],
        "concepts": ["RAG", "embeddings", "streaming", "async", "learning"],
        "keywords": ["learning", "RAG", "embeddings", "experiments", "sandbox"],
        "question_types": ["what", "how"],
        "intent_relevance": {"project_deepdive": 0.8, "skill_assessment": 0.7},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "document_dispatch.md": {
        "title": "Automated Document Dispatch System",
        "subcategory": "backend",
        "content_type": "technical",
        "section": "Projects",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "Kogta Financial",
        "technologies": ["FastAPI", "MongoDB", "SQS", "S3", "WeasyPrint", "Kubernetes", "Jenkins"],
        "concepts": ["automation", "PDF", "queue", "async", "multi-channel", "retry"],
        "keywords": ["document", "PDF", "automation", "SQS", "parallel", "dispatch"],
        "question_types": ["what", "how", "architecture"],
        "intent_relevance": {"project_deepdive": 1.0, "code_walkthrough": 0.9, "skill_assessment": 0.8},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": True,
        "detail_level": "deep",
    },
    "communication_platform.md": {
        "title": "Multi-Channel Communication Platform",
        "subcategory": "backend",
        "content_type": "technical",
        "section": "Projects",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "Kogta Financial",
        "technologies": ["FastAPI", "MongoDB", "SQS", "MySQL", "MSSQL", "RedShift", "OpenSearch", "Kubernetes"],
        "concepts": ["messaging", "webhook", "plugin", "multi-db", "async", "batch"],
        "keywords": ["whatsapp", "SMS", "RCS", "messaging", "webhook", "platform"],
        "question_types": ["what", "how", "architecture"],
        "intent_relevance": {"project_deepdive": 1.0, "code_walkthrough": 0.8, "skill_assessment": 0.9},
        "has_code": False,
        "has_metrics": True,
        "has_architecture": True,
        "detail_level": "deep",
    },
    # === CODE SNIPPETS ===
    "token_management.md": {
        "title": "Token Management for LLMs",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-12",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "tiktoken", "OpenAI"],
        "concepts": ["token", "context", "truncation", "cost"],
        "keywords": ["token", "tiktoken", "context", "truncation", "cost"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.8},
        "has_code": True,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "hybrid_search.md": {
        "title": "Hybrid Search Pattern (RAG)",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-12",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "ChromaDB", "OpenAI"],
        "concepts": ["hybrid", "semantic", "keyword", "BM25", "retrieval"],
        "keywords": ["hybrid", "search", "semantic", "keyword", "BM25"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.9},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "sqs_queue_processing.md": {
        "title": "SQS Queue Processing Pattern",
        "subcategory": "backend",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "AWS", "SQS", "asyncio"],
        "concepts": ["queue", "async", "batch", "FIFO", "consumer"],
        "keywords": ["SQS", "queue", "consumer", "batch", "async"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.7},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "parallel_pdf_generation.md": {
        "title": "Parallel PDF Generation with asyncio",
        "subcategory": "backend",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "asyncio", "WeasyPrint", "Jinja2"],
        "concepts": ["async", "parallel", "PDF", "executor", "performance"],
        "keywords": ["PDF", "parallel", "async", "executor", "weasyprint"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.8},
        "has_code": True,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "webhook_handler.md": {
        "title": "Webhook Handler with Idempotent Processing",
        "subcategory": "backend",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-03",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "FastAPI", "MongoDB", "SQS"],
        "concepts": ["webhook", "idempotent", "status", "priority", "queue"],
        "keywords": ["webhook", "idempotent", "status", "priority", "delivery"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.8},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "deep",
    },
    "rag_pipeline.md": {
        "title": "Complete RAG Pipeline",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-11",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "OpenAI", "ChromaDB"],
        "concepts": ["RAG", "retrieval", "augmentation", "generation", "embeddings"],
        "keywords": ["RAG", "pipeline", "retrieval", "embeddings", "generation"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.9},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "chunking.md": {
        "title": "Document Chunking Strategies",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-11",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python"],
        "concepts": ["chunking", "embeddings", "RAG", "semantic"],
        "keywords": ["chunking", "split", "paragraph", "sentence", "embeddings"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.7},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "rate_limiting.md": {
        "title": "Rate Limiting Implementation",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-11",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "asyncio", "OpenAI"],
        "concepts": ["rate_limit", "semaphore", "async", "concurrency"],
        "keywords": ["rate", "limit", "semaphore", "async", "concurrent"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.6},
        "has_code": True,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "async_calls.md": {
        "title": "Async LLM Calls",
        "subcategory": "genai",
        "content_type": "code",
        "section": "Code Snippets",
        "date_start": "2025-11",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "asyncio", "OpenAI"],
        "concepts": ["async", "concurrent", "performance", "batch"],
        "keywords": ["async", "concurrent", "batch", "performance", "LLM"],
        "question_types": ["how", "show"],
        "intent_relevance": {"code_walkthrough": 1.0, "project_deepdive": 0.6},
        "has_code": True,
        "has_metrics": True,
        "has_architecture": False,
        "detail_level": "medium",
    },
    # === ASSESSMENTS ===
    "genai_fit.md": {
        "title": "GenAI Engineer Role Fit Assessment",
        "subcategory": "genai",
        "content_type": "summary",
        "section": "Assessments",
        "date_start": "2025-01",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "OpenAI", "ChromaDB", "LangChain", "FastAPI"],
        "concepts": ["RAG", "LLM", "assessment", "fit", "skills"],
        "keywords": ["genai", "role", "fit", "assessment", "RAG", "LLM"],
        "question_types": ["what", "fit"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.8},
        "has_code": False,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
    "backend_fit.md": {
        "title": "Backend Engineer Role Fit Assessment",
        "subcategory": "backend",
        "content_type": "summary",
        "section": "Assessments",
        "date_start": "2021-04",
        "date_end": "present",
        "recency_score": 1.0,
        "company": "personal",
        "technologies": ["Python", "FastAPI", "MongoDB", "MySQL", "Kubernetes", "AWS"],
        "concepts": ["backend", "assessment", "fit", "skills", "microservices"],
        "keywords": ["backend", "role", "fit", "assessment", "senior", "engineer"],
        "question_types": ["what", "fit"],
        "intent_relevance": {"skill_assessment": 1.0, "quick_answer": 0.8},
        "has_code": False,
        "has_metrics": False,
        "has_architecture": False,
        "detail_level": "medium",
    },
}
